### ISSUE TITLE
Why not call this package 'pwsh' ?

### ISSUE THREAD

**Issue by fearthecowboy** [cspotcode/npm-get-powershell#13]
Before I saw this, I was going to go build the same thing, but I was going to call it `pwsh` . 

I'm still half tempted to push a clone of this to `pwsh` in npm. 😀

**Comment by cspotcode** [comment]
This package is the first result when you search for pwsh so I think we're fine.

https://www.npmjs.com/search?q=pwsh

The name `get-powershell` was chosen because technically it doesn't contain PowerShell; it downloads it seperately.  It's a silly distinction, but that's the reason: it behaves a bit differently than most npm packages.  Not a strong reason, but *meh* I don't really care about changing it at this point.

**Comment by fearthecowboy** [comment]
I just thought of another reason it'd be nice if this was published as `pwsh` -- done correctly, you'd be able to use `npx` to run a powershell script. When the `package` name `===` the `bin` name, `npx`  will cache install the package and then run `pwsh` when done. Doesn't even pollute the `PATH`.

``` powershell
> npx pwsh get-item --recursive ./  
```

**Comment by cspotcode** [comment]
That's a great point.  Ok, I'll do it.

**Comment by fearthecowboy** [comment]
#SQUEEEEEE!

💃 
🎆 
👍 
🎆 

Plus, a free pony ride! 🏇

**Comment by cspotcode** [comment]
Done!  Thanks for your patience; getting tests running on Travis took way longer than anticipated.
